### ISSUE TITLE
'strip_common_prefix' removing too much

### ISSUE THREAD

**Issue by iBotPeaches** [getsentry/sentry-fastlane-plugin#199]
### Environment

v1 

### Steps to Reproduce

```yaml
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_ORG: redacted
      with:
        environment: ${{ inputs.env_name }}
        version: ${{ inputs.version }}
        sourcemaps: './public/js ./public/assets/js'
        strip_common_prefix: 'true'
        url_prefix: '~'
```

### Expected Result

Files would get uploaded stripping the common prefix (ie `public`), but instead get stripped way too much. If we look at the directory breakdown we have:

```
public/assets/js/*.chunk.js
public/js/*.js
```

### Actual Result

<img width="776" alt="Screenshot 2023-07-17 at 12 04 12 PM" src="https://github.com/getsentry/sentry-fastlane-plugin/assets/611784/d10deb97-f21c-4d60-a360-baf885d3ad21">

Basically we see it stripped way more than I expect. I would imagine the only common difference between those two above paths is up to the `public` part.

I expected to get files uploaded like:

 * `assets/js/*.chunk.js`
 * `js/*.js`
 
However, it stripped `assets/js` from the first and `js` from the 2nd. Which of course in my eyes is the reason the sourcemaps are not working
 
 > We've encountered 1 problem un-minifying your applications source code!
